#!/bin/bash
set -e

exec > >(tee /var/log/user-data.log|logger -t user-data -s 2>/dev/console) 2>&1

echo "Starting Coturn installation..."

# Update system
dnf update -y
dnf install -y docker jq certbot bind-utils

# Start Docker
systemctl start docker
systemctl enable docker

# Get metadata (IMDSv2 required)
TOKEN=$(curl -s -X PUT "http://169.254.169.254/latest/api/token" -H "X-aws-ec2-metadata-token-ttl-seconds: 21600")
PRIVATE_IP=$(curl -s -H "X-aws-ec2-metadata-token: $TOKEN" http://169.254.169.254/latest/meta-data/local-ipv4)

DOMAIN="${domain}"
TURN_DOMAIN="turn.$DOMAIN"
PUBLIC_IP="${public_ip}"
TURN_SECRET="${turn_secret}"

echo "Configuration:"
echo "  TURN Domain: $TURN_DOMAIN"
echo "  Public IP: $PUBLIC_IP"
echo "  Private IP: $PRIVATE_IP"

# Wait for DNS to propagate
echo "Waiting for DNS propagation..."
for i in {1..30}; do
  RESOLVED_IP=$(dig +short $TURN_DOMAIN || true)
  if [ "$RESOLVED_IP" = "$PUBLIC_IP" ]; then
    echo "DNS resolved correctly: $TURN_DOMAIN -> $PUBLIC_IP"
    break
  fi
  echo "Waiting for DNS... (attempt $i/30, got: $RESOLVED_IP)"
  sleep 10
done

# Verify DNS resolved - fail fast if not
RESOLVED_IP=$(dig +short $TURN_DOMAIN || true)
if [ "$RESOLVED_IP" != "$PUBLIC_IP" ]; then
  echo "ERROR: DNS did not resolve correctly after 5 minutes"
  echo "Expected: $PUBLIC_IP"
  echo "Got: $RESOLVED_IP"
  echo "Let's Encrypt will fail without correct DNS. Aborting."
  exit 1
fi

# Get Let's Encrypt certificate
echo "Obtaining Let's Encrypt certificate..."
certbot certonly --standalone \
  --non-interactive \
  --agree-tos \
  --email ${admin_email} \
  -d $TURN_DOMAIN || {
    echo "ERROR: Failed to obtain certificate"
    echo "Check DNS resolution and port 80 accessibility"
    exit 1
  }

echo "Certificate obtained successfully"

# Create coturn config directory
mkdir -p /opt/coturn
cd /opt/coturn

# Create turnserver.conf
cat > turnserver.conf << EOF
# Coturn configuration for WorkAdventure
# Generated by Terraform user_data script

# Listener settings - bind to all interfaces for both regular and TLS
listening-port=3478
tls-listening-port=5349
listening-ip=0.0.0.0
external-ip=$PUBLIC_IP/$PRIVATE_IP
relay-ip=$PRIVATE_IP

# Also listen for TLS on alt port (some clients prefer this)
alt-tls-listening-port=443

# Min/max ports for relay
min-port=49152
max-port=65535

# Realm (domain)
realm=$TURN_DOMAIN

# TLS certificates - must be readable by coturn user
cert=/etc/letsencrypt/live/$TURN_DOMAIN/fullchain.pem
pkey=/etc/letsencrypt/live/$TURN_DOMAIN/privkey.pem

# Use static-auth-secret for time-limited credentials
use-auth-secret
static-auth-secret=$TURN_SECRET

# Logging
log-file=stdout
verbose

# Security
no-multicast-peers
no-cli
fingerprint

# Deny relay to private IP ranges (security)
denied-peer-ip=10.0.0.0-10.255.255.255
denied-peer-ip=172.16.0.0-172.31.255.255
denied-peer-ip=192.168.0.0-192.168.255.255
denied-peer-ip=127.0.0.0-127.255.255.255

# Performance
proc-quota=60
max-bps=0
total-quota=100
EOF

echo "Starting Coturn container..."

# Copy certificates to a location readable by the container
# The coturn/coturn image runs as user 'turnserver' (uid 65534)
mkdir -p /opt/coturn/certs
cp /etc/letsencrypt/live/$TURN_DOMAIN/fullchain.pem /opt/coturn/certs/
cp /etc/letsencrypt/live/$TURN_DOMAIN/privkey.pem /opt/coturn/certs/
chmod 644 /opt/coturn/certs/*.pem

# Update turnserver.conf to use the copied certs
sed -i "s|/etc/letsencrypt/live/$TURN_DOMAIN/fullchain.pem|/etc/coturn/certs/fullchain.pem|g" turnserver.conf
sed -i "s|/etc/letsencrypt/live/$TURN_DOMAIN/privkey.pem|/etc/coturn/certs/privkey.pem|g" turnserver.conf

# Run coturn in Docker
docker run -d \
  --name coturn \
  --network host \
  --restart unless-stopped \
  -v /opt/coturn/turnserver.conf:/etc/turnserver.conf:ro \
  -v /opt/coturn/certs:/etc/coturn/certs:ro \
  coturn/coturn:latest \
  -c /etc/turnserver.conf

# Wait for container to start
sleep 5

# Check container status
if docker ps | grep -q coturn; then
  echo "Coturn container started successfully"
else
  echo "ERROR: Coturn container failed to start"
  docker logs coturn
  exit 1
fi

# Set up certificate renewal cron with cert copying
mkdir -p /etc/cron.d
cat > /opt/coturn/renew-certs.sh << 'RENEWSCRIPT'
#!/bin/bash
TURN_DOMAIN="turn.${domain}"
certbot renew --quiet
cp /etc/letsencrypt/live/$TURN_DOMAIN/fullchain.pem /opt/coturn/certs/
cp /etc/letsencrypt/live/$TURN_DOMAIN/privkey.pem /opt/coturn/certs/
chmod 644 /opt/coturn/certs/*.pem
docker restart coturn
RENEWSCRIPT
chmod +x /opt/coturn/renew-certs.sh

cat > /etc/cron.d/certbot-renew << 'CRON'
0 3 * * * root /opt/coturn/renew-certs.sh
CRON
chmod 644 /etc/cron.d/certbot-renew

echo ""
echo "========================================"
echo "Coturn installation complete!"
echo "========================================"
echo "TURN domain: $TURN_DOMAIN"
echo "TURN URL: turn:$TURN_DOMAIN:3478"
echo "TURNS URL: turns:$TURN_DOMAIN:5349"
echo ""
echo "Test with: nc -z $TURN_DOMAIN 3478"
echo "========================================"
