# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
from . import _utilities
import typing
# Export this package's modules as members:
from .action import *
from .compute_env import *
from .credential import *
from .data_link import *
from .datasets import *
from .get_action import *
from .get_compute_env import *
from .get_credential import *
from .get_data_link import *
from .get_dataset import *
from .get_labels import *
from .get_orgs import *
from .get_pipeline import *
from .get_pipeline_secret import *
from .get_studios import *
from .get_teams import *
from .get_tokens import *
from .get_user import *
from .get_user_workspaces import *
from .get_workflows import *
from .get_workspace import *
from .get_workspaces import *
from .labels import *
from .orgs import *
from .pipeline import *
from .pipeline_secret import *
from .provider import *
from .studios import *
from .teams import *
from .tokens import *
from .workflows import *
from .workspace import *
from ._inputs import *
from . import outputs

# Make subpackages available:
if typing.TYPE_CHECKING:
    import pulumi_seqera.config as __config
    config = __config
else:
    config = _utilities.lazy_import('pulumi_seqera.config')

_utilities.register(
    resource_modules="""
[
 {
  "pkg": "seqera",
  "mod": "index/action",
  "fqn": "pulumi_seqera",
  "classes": {
   "seqera:index/action:Action": "Action"
  }
 },
 {
  "pkg": "seqera",
  "mod": "index/computeEnv",
  "fqn": "pulumi_seqera",
  "classes": {
   "seqera:index/computeEnv:ComputeEnv": "ComputeEnv"
  }
 },
 {
  "pkg": "seqera",
  "mod": "index/credential",
  "fqn": "pulumi_seqera",
  "classes": {
   "seqera:index/credential:Credential": "Credential"
  }
 },
 {
  "pkg": "seqera",
  "mod": "index/dataLink",
  "fqn": "pulumi_seqera",
  "classes": {
   "seqera:index/dataLink:DataLink": "DataLink"
  }
 },
 {
  "pkg": "seqera",
  "mod": "index/datasets",
  "fqn": "pulumi_seqera",
  "classes": {
   "seqera:index/datasets:Datasets": "Datasets"
  }
 },
 {
  "pkg": "seqera",
  "mod": "index/labels",
  "fqn": "pulumi_seqera",
  "classes": {
   "seqera:index/labels:Labels": "Labels"
  }
 },
 {
  "pkg": "seqera",
  "mod": "index/orgs",
  "fqn": "pulumi_seqera",
  "classes": {
   "seqera:index/orgs:Orgs": "Orgs"
  }
 },
 {
  "pkg": "seqera",
  "mod": "index/pipeline",
  "fqn": "pulumi_seqera",
  "classes": {
   "seqera:index/pipeline:Pipeline": "Pipeline"
  }
 },
 {
  "pkg": "seqera",
  "mod": "index/pipelineSecret",
  "fqn": "pulumi_seqera",
  "classes": {
   "seqera:index/pipelineSecret:PipelineSecret": "PipelineSecret"
  }
 },
 {
  "pkg": "seqera",
  "mod": "index/studios",
  "fqn": "pulumi_seqera",
  "classes": {
   "seqera:index/studios:Studios": "Studios"
  }
 },
 {
  "pkg": "seqera",
  "mod": "index/teams",
  "fqn": "pulumi_seqera",
  "classes": {
   "seqera:index/teams:Teams": "Teams"
  }
 },
 {
  "pkg": "seqera",
  "mod": "index/tokens",
  "fqn": "pulumi_seqera",
  "classes": {
   "seqera:index/tokens:Tokens": "Tokens"
  }
 },
 {
  "pkg": "seqera",
  "mod": "index/workflows",
  "fqn": "pulumi_seqera",
  "classes": {
   "seqera:index/workflows:Workflows": "Workflows"
  }
 },
 {
  "pkg": "seqera",
  "mod": "index/workspace",
  "fqn": "pulumi_seqera",
  "classes": {
   "seqera:index/workspace:Workspace": "Workspace"
  }
 }
]
""",
    resource_packages="""
[
 {
  "pkg": "seqera",
  "token": "pulumi:providers:seqera",
  "fqn": "pulumi_seqera",
  "class": "Provider"
 }
]
"""
)
