[project]
name = "pulumi-state"
version = "0.1.0"
description = "Bootstrap project to create S3 bucket for Pulumi state storage"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "pulumi>=3.173.0,<4.0.0",
    "pulumi-aws>=6.81.0,<7.0.0",
]
