#!/bin/bash
set -e

# Log everything
exec > >(tee /var/log/user-data.log|logger -t user-data -s 2>/dev/console) 2>&1

echo "Starting WorkAdventure installation..."

# Update system
dnf update -y
dnf install -y docker git jq

# Start Docker
systemctl start docker
systemctl enable docker

# Install docker-compose
curl -L "https://github.com/docker/compose/releases/latest/download/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
chmod +x /usr/local/bin/docker-compose

# Create app directory
mkdir -p /opt/workadventure
cd /opt/workadventure

# Clone WorkAdventure
git clone --depth 1 https://github.com/workadventure/workadventure.git
cd workadventure/contrib/docker

# Generate random values for secrets
MAP_STORAGE_PASSWORD=$(openssl rand -base64 16 | tr -dc 'a-zA-Z0-9' | head -c 16)
ROOM_API_SECRET=$(openssl rand -hex 32)

# Create .env file
# Note: Variables like ${domain} are replaced by Terraform templatefile()
# Shell variables like $MAP_STORAGE_PASSWORD are evaluated at runtime
cat > .env << EOF
# =============================================================================
# WorkAdventure Configuration
# Generated by Terraform user_data script
# =============================================================================

# Domain - Use the app subdomain since ALB routes app.domain to this instance
# WorkAdventure's Traefik routes based on Host header matching DOMAIN
DOMAIN=app.${domain}

# Version
VERSION=master

# Logging
LOG_LEVEL=WARN

# Ports - ALB forwards to port 80
HTTP_PORT=80
HTTPS_PORT=443
GRPC_PORT=50051

# Data directory
DATA_DIR=/opt/workadventure/data

# Restart policy
RESTART_POLICY=unless-stopped

# =============================================================================
# Security
# =============================================================================
SECRET_KEY=${workadventure_secret_key}
ROOM_API_SECRET_KEY=$ROOM_API_SECRET

# Map storage authentication
MAP_STORAGE_AUTHENTICATION_USER=admin
MAP_STORAGE_AUTHENTICATION_PASSWORD=$MAP_STORAGE_PASSWORD

# =============================================================================
# URLs and Endpoints
# =============================================================================
# Map storage API (internal WorkAdventure service)
PUBLIC_MAP_STORAGE_URL=https://map-storage.${domain}

# START_ROOM_URL - The default map loaded when users visit the app
# IMPORTANT: This MUST point to a valid, publicly accessible map JSON file.
# Format: /_/global/<public-url-to-map.json>
# Using our S3 bucket which hosts the maps (synced via scripts/sync-maps.sh)
START_ROOM_URL=/_/global/${s3_bucket}.s3.eu-west-1.amazonaws.com/maps/default/map.json

# =============================================================================
# Server Branding
# =============================================================================
SERVER_NAME=nf-core Hackathon
SERVER_MOTD=Welcome to the nf-core hackathon! Collaborate on bioinformatics pipelines.
SERVER_ICON=https://${s3_bucket}.s3.eu-west-1.amazonaws.com/assets/logos/nf-core-logo-square.png
CONTACT_URL=https://nf-co.re/join#slack

# =============================================================================
# Features
# =============================================================================
ENABLE_CHAT=true
ENABLE_CHAT_UPLOAD=false
ENABLE_CHAT_ONLINE_LIST=true
ENABLE_CHAT_DISCONNECTED_LIST=true
ENABLE_MAP_EDITOR=false
ENABLE_REPORT_ISSUES_MENU=false

# Disable unused features
DISABLE_ANONYMOUS=false
DISABLE_NOTIFICATIONS=false

# =============================================================================
# ACME / Let's Encrypt (for Traefik)
# =============================================================================
ACME_EMAIL=${admin_email}

%{ if livekit_url != "" ~}
# =============================================================================
# LiveKit Configuration (for proximity video)
# =============================================================================
LIVEKIT_URL=${livekit_url}
LIVEKIT_API_KEY=${livekit_api_key}
LIVEKIT_API_SECRET=${livekit_api_secret}
%{ endif ~}

%{ if jitsi_url != "" ~}
# =============================================================================
# Jitsi Configuration (for meeting room zones)
# =============================================================================
JITSI_URL=${jitsi_url}
JITSI_PRIVATE_MODE=false
%{ else ~}
JITSI_URL=
%{ endif ~}

%{ if turn_server != "" ~}
# =============================================================================
# TURN Configuration
# =============================================================================
TURN_SERVER=${turn_server}
TURN_STATIC_AUTH_SECRET=${turn_secret}
%{ endif ~}

# =============================================================================
# Optional integrations (disabled)
# =============================================================================
KLAXOON_ENABLED=false
YOUTUBE_ENABLED=true
GOOGLE_DRIVE_ENABLED=false
GOOGLE_DOCS_ENABLED=false
GOOGLE_SHEETS_ENABLED=false
GOOGLE_SLIDES_ENABLED=false
ERASER_ENABLED=false
EXCALIDRAW_ENABLED=true
CARDS_ENABLED=false
TLDRAW_ENABLED=false
EOF

# Create data directories
mkdir -p /opt/workadventure/data/letsencrypt

# =============================================================================
# GitHub OAuth Authentication (Milestone 8)
# =============================================================================
# Download custom templates for oauth2-proxy from S3
mkdir -p /opt/workadventure/oauth2-templates
S3_URL="https://${s3_bucket}.s3.${aws_region}.amazonaws.com"
curl -sL "$S3_URL/assets/templates/sign_in.html" | sed "s|__S3_BUCKET_URL__|$S3_URL|g" > /opt/workadventure/oauth2-templates/sign_in.html
curl -sL "$S3_URL/assets/templates/error.html" > /opt/workadventure/oauth2-templates/error.html

# Create a modified docker-compose that works behind ALB with oauth2-proxy
# The ALB terminates TLS, so Traefik only needs HTTP
# NOTE: Do NOT enable Let's Encrypt here - the ALB has an ACM certificate
# We still define websecure entrypoint (on port 8443) so prod.yaml labels work,
# but ALB only sends traffic to port 80
cat > docker-compose.override.yaml << 'OVERRIDE'
version: "3.6"
services:
  reverse-proxy:
    command:
      - --log.level=$${LOG_LEVEL:-WARN}
      - --providers.docker
      - --providers.docker.exposedbydefault=false
      # HTTP entrypoint - ALB sends traffic here
      - --entryPoints.web.address=:80
      # Define websecure entrypoint so prod.yaml service labels work
      # But ALB doesn't send traffic here - it handles TLS itself
      - --entryPoints.websecure.address=:8443
      - --entryPoints.grpc.address=:50051
      # NO Let's Encrypt - ALB uses ACM certificate
OVERRIDE

# Append oauth2-proxy service to docker-compose.override.yaml
# Using heredoc with variable substitution for Terraform values
cat >> docker-compose.override.yaml << EOF

  # GitHub OAuth2 Proxy (Milestone 8)
  # Protects the main app - only nf-core org members can access
  oauth2-proxy:
    image: quay.io/oauth2-proxy/oauth2-proxy:v7.14.2
    container_name: oauth2-proxy
    restart: unless-stopped
    command:
      - --provider=github
      - --github-org=${github_org}
      - --client-id=${github_oauth_client_id}
      - --client-secret=${github_oauth_client_secret}
      - --cookie-secret=${oauth2_proxy_cookie_secret}
      - --cookie-secure=true
      - --cookie-domain=.${domain}
      - --whitelist-domain=.${domain}
      - --email-domain=*
      - --upstream=http://play:3000
      - --http-address=0.0.0.0:4180
      - --reverse-proxy=true
      - --custom-templates-dir=/templates
      # Note: NOT using --skip-provider-button so social previews work
      # The sign_in.html template uses JavaScript to auto-redirect for real users
    volumes:
      - /opt/workadventure/oauth2-templates:/templates:ro
    labels:
      - "traefik.enable=true"
      # Route app.domain through oauth2-proxy (except WebSocket, static resources, and favicon)
      - "traefik.http.routers.oauth2-proxy.rule=Host(\"app.${domain}\") && !PathPrefix(\"/ws\") && !PathPrefix(\"/resources\") && !PathPrefix(\"/static\") && !Path(\"/favicon.ico\") && !PathPrefix(\"/manifest\")"
      - "traefik.http.routers.oauth2-proxy.entrypoints=web"
      - "traefik.http.services.oauth2-proxy.loadbalancer.server.port=4180"
      - "traefik.http.routers.oauth2-proxy.priority=100"

  # Override play service to handle WebSocket and static resource paths directly (bypassing oauth2-proxy)
  # WebSocket: oauth2-proxy doesn't properly handle WebSocket upgrade requests
  # Static resources: /resources/* and /static/* don't need auth protection
  # NOTE: WebSocket server runs on port 3001, HTTP server on port 3000
  play:
    labels:
      - "traefik.enable=true"
      # WebSocket router - bypasses oauth2-proxy, routes to port 3001
      - "traefik.http.routers.play-ws.rule=Host(\"app.${domain}\") && PathPrefix(\"/ws\")"
      - "traefik.http.routers.play-ws.entrypoints=web"
      - "traefik.http.routers.play-ws.priority=200"
      - "traefik.http.services.play-ws.loadbalancer.server.port=3001"
      # Static resources router - bypasses oauth2-proxy, routes to port 3000
      - "traefik.http.routers.play-static.rule=Host(\"app.${domain}\") && (PathPrefix(\"/resources\") || PathPrefix(\"/static\") || Path(\"/favicon.ico\") || PathPrefix(\"/manifest\"))"
      - "traefik.http.routers.play-static.entrypoints=web"
      - "traefik.http.routers.play-static.priority=200"
      - "traefik.http.services.play-static.loadbalancer.server.port=3000"
EOF

# Start the services
echo "Starting WorkAdventure services..."
# Use docker-compose.prod.yaml with our override
# The override removes Let's Encrypt since ALB handles TLS with ACM certificate
docker-compose -f docker-compose.prod.yaml -f docker-compose.override.yaml up -d

# Wait for services to be ready
echo "Waiting for services to start..."
sleep 30

# Fix missing webrtc-in.mp3 (renamed in newer versions to webrtc-in-ding.mp3)
# Some client code still references the old filename
echo "Applying compatibility fixes..."
docker exec docker-play-1 ln -sf /usr/src/play/dist/public/resources/objects/webrtc-in-ding.mp3 /usr/src/play/dist/public/resources/objects/webrtc-in.mp3 2>/dev/null || true

# Check service status
docker-compose -f docker-compose.prod.yaml -f docker-compose.override.yaml ps

echo "WorkAdventure installation complete!"
echo "Access URL: https://app.${domain}"
