[project]
name = "github-teams"
version = "0.1.0"
description = "Pulumi project for GitHub teams management"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "pulumi>=3.173.0",
    "pulumi-github>=6.7.2",
    "ruff>=0.3.7",
    "PyYAML>=6.0",
    "types-PyYAML",
] 