[project]
authors = ["Edmund Miller <git@edmundmiller.dev>"]
channels = ["conda-forge", "bioconda"]
description = "Add a short description here"
name = "steampipe"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]
plugins = "steampipe plugin install github twitter"
twitter = "steampipe query twitter_users.sql --output json | jq '.rows[0] + {timestamp: now|tostring}' >> twitter_users.json"
github = "steampipe query github.sql --output json | jq '.rows[0] + {timestamp: now|tostring}' >> github.json"

[dependencies]
steampipe = ">=0.23.5,<0.24"
jq = ">=1.7.1,<2"
huggingface_hub = ">=0.24.6,<0.25"
