[project]
authors = ["Edmund Miller <git@edmundmiller.dev>"]
channels = ["conda-forge", "bioconda"]
description = "Add a short description here"
name = "steampipe"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]
plugins = "steampipe plugin install github twitter slack --progress=false"
twitter = "steampipe query twitter_users.sql --output json | jq '.rows[0].public_metrics + {timestamp: now|tostring}' >> hf_stats/steampipe/twitter_users.json"
twitter_hc = { cmd = "curl -fsS -m 10 --retry 5 -o /dev/null https://hc-ping.com/39c783d5-b697-4eb5-b677-05bae13a2490", depends_on = ["twitter"] }
github = "steampipe query github.sql --output json | jq '.rows[0] + {timestamp: now|tostring}' >> hf_stats/steampipe/github.json"
github_hc = { cmd = "curl -fsS -m 10 --retry 5 -o /dev/null https://hc-ping.com/017c8a09-9531-4206-a479-aa51a2209931", depends_on = ["github"] }
slack_active = "steampipe query slack_active_users.sql --output json | jq '.rows[0] + {timestamp: now|tostring}' >> hf_stats/steampipe/slack_active_users.json"
slack_total = "steampipe query slack_total_users.sql --output json | jq '.rows[0] + {timestamp: now|tostring}' >> hf_stats/steampipe/slack_total_users.json"
slack_hc = { cmd = "curl -fsS -m 10 --retry 5 -o /dev/null https://hc-ping.com/af9808d6-6dd7-4e8d-8fc7-c132fc579597", depends_on = ["slack_active", "slack_total"] }
download_hf = "huggingface-cli download nf-core/stats --local-dir hf_stats --repo-type dataset --quiet"
upload_hf = "huggingface-cli upload nf-core/stats hf_stats --repo-type dataset --quiet"

[dependencies]
steampipe = ">=0.23.5,<0.24"
jq = ">=1.7.1,<2"
huggingface_hub = ">=0.24.6,<0.25"
