name: Stats

on:
  schedule: # every day at 2am and 2pm
    - cron: "0 2,14 * * *"
  pull_request:
    paths:
      - "stats/steampipe/**"
  workflow_dispatch:
  repository_dispatch:
    types: [update-website]

env:
  HF_TOKEN: ${{ secrets.HF_TOKEN }}

jobs:
  update:
    name: Update
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: prefix-dev/setup-pixi@v0.8.1
        with:
          cache: true
      - run: pixi run download_hf
      - run: pixi run github
      # TODO - run: pixi run twitter
      # TODO - run: pixi run slack
      - run: pixi run upload_hf
